import type { Difficulty } from '@/gameplay'

export interface ListeningPrompt {
  id: number
  difficulty: Difficulty
  audioText: string
  audioLang: string
  question: string
  choices: [string, string, string]
  correctIndex: 0 | 1 | 2
}

export const LISTENING_PROMPTS: ListeningPrompt[] = [
  /* ── EASY (40 prompts) ───────────────────── */
  { id: 1, difficulty: 'easy', audioText: 'Merhaba, nasılsın?', audioLang: 'tr-TR', question: 'What is being said?', choices: ['Hello, how are you?', 'Goodbye, see you!', 'Good night!'], correctIndex: 0 },
  { id: 2, difficulty: 'easy', audioText: 'Benim adım Ali.', audioLang: 'tr-TR', question: 'What does the speaker say?', choices: ['I am hungry.', 'My name is Ali.', 'I am tired.'], correctIndex: 1 },
  { id: 3, difficulty: 'easy', audioText: 'Teşekkür ederim.', audioLang: 'tr-TR', question: 'What did you hear?', choices: ['I am sorry.', 'Please help me.', 'Thank you.'], correctIndex: 2 },
  { id: 4, difficulty: 'easy', audioText: 'Günaydın!', audioLang: 'tr-TR', question: 'What greeting is this?', choices: ['Good morning!', 'Good evening!', 'Good night!'], correctIndex: 0 },
  { id: 5, difficulty: 'easy', audioText: 'Evet, anlıyorum.', audioLang: 'tr-TR', question: 'What is the response?', choices: ['No, I don\'t know.', 'Yes, I understand.', 'Maybe later.'], correctIndex: 1 },
  { id: 6, difficulty: 'easy', audioText: 'Su istiyorum.', audioLang: 'tr-TR', question: 'What does the speaker want?', choices: ['Tea', 'Coffee', 'Water'], correctIndex: 2 },
  { id: 7, difficulty: 'easy', audioText: 'Bugün hava güzel.', audioLang: 'tr-TR', question: 'What is the topic?', choices: ['The weather is nice today.', 'I am going to school.', 'The food is ready.'], correctIndex: 0 },
  { id: 8, difficulty: 'easy', audioText: 'Ben öğrenciyim.', audioLang: 'tr-TR', question: 'Who is speaking?', choices: ['A teacher', 'A student', 'A doctor'], correctIndex: 1 },
  { id: 9, difficulty: 'easy', audioText: 'Hoşça kal!', audioLang: 'tr-TR', question: 'What is being said?', choices: ['Welcome!', 'Come here!', 'Goodbye!'], correctIndex: 2 },
  { id: 10, difficulty: 'easy', audioText: 'Bir çay lütfen.', audioLang: 'tr-TR', question: 'What is ordered?', choices: ['One tea, please.', 'One coffee, please.', 'One juice, please.'], correctIndex: 0 },
  { id: 11, difficulty: 'easy', audioText: 'Bu kedi çok güzel.', audioLang: 'tr-TR', question: 'What animal is mentioned?', choices: ['Dog', 'Cat', 'Bird'], correctIndex: 1 },
  { id: 12, difficulty: 'easy', audioText: 'Annem evde.', audioLang: 'tr-TR', question: 'Where is the mother?', choices: ['At school', 'At work', 'At home'], correctIndex: 2 },
  { id: 13, difficulty: 'easy', audioText: 'Ben Türküm.', audioLang: 'tr-TR', question: 'What did the speaker say?', choices: ['I am Turkish.', 'I am German.', 'I am French.'], correctIndex: 0 },
  { id: 14, difficulty: 'easy', audioText: 'Saat on iki.', audioLang: 'tr-TR', question: 'What time is it?', choices: ['Ten o\'clock', 'Twelve o\'clock', 'Two o\'clock'], correctIndex: 1 },
  { id: 15, difficulty: 'easy', audioText: 'Hava soğuk.', audioLang: 'tr-TR', question: 'How is the weather?', choices: ['Hot', 'Rainy', 'Cold'], correctIndex: 2 },
  { id: 16, difficulty: 'easy', audioText: 'Ekmek aldım.', audioLang: 'tr-TR', question: 'What did the speaker buy?', choices: ['Bread', 'Milk', 'Eggs'], correctIndex: 0 },
  { id: 17, difficulty: 'easy', audioText: 'Kapıyı aç.', audioLang: 'tr-TR', question: 'What is the instruction?', choices: ['Close the window.', 'Open the door.', 'Turn off the light.'], correctIndex: 1 },
  { id: 18, difficulty: 'easy', audioText: 'Çok yorgunum.', audioLang: 'tr-TR', question: 'How does the speaker feel?', choices: ['Happy', 'Hungry', 'Tired'], correctIndex: 2 },
  { id: 19, difficulty: 'easy', audioText: 'Okula gidiyorum.', audioLang: 'tr-TR', question: 'Where is the speaker going?', choices: ['To school', 'To the market', 'To the park'], correctIndex: 0 },
  { id: 20, difficulty: 'easy', audioText: 'İki kardeşim var.', audioLang: 'tr-TR', question: 'How many siblings?', choices: ['One', 'Two', 'Three'], correctIndex: 1 },
  { id: 21, difficulty: 'easy', audioText: 'Babam doktor.', audioLang: 'tr-TR', question: 'What is the father\'s job?', choices: ['Teacher', 'Engineer', 'Doctor'], correctIndex: 2 },
  { id: 22, difficulty: 'easy', audioText: 'Bu kitap güzel.', audioLang: 'tr-TR', question: 'What is being described?', choices: ['A book', 'A movie', 'A song'], correctIndex: 0 },
  { id: 23, difficulty: 'easy', audioText: 'Yumurta yedim.', audioLang: 'tr-TR', question: 'What did the speaker eat?', choices: ['Bread', 'Eggs', 'Cheese'], correctIndex: 1 },
  { id: 24, difficulty: 'easy', audioText: 'Köpek havlıyor.', audioLang: 'tr-TR', question: 'What is the dog doing?', choices: ['Sleeping', 'Running', 'Barking'], correctIndex: 2 },
  { id: 25, difficulty: 'easy', audioText: 'Pencereyi kapat.', audioLang: 'tr-TR', question: 'What should be done?', choices: ['Close the window.', 'Open the door.', 'Turn on the TV.'], correctIndex: 0 },
  { id: 26, difficulty: 'easy', audioText: 'Süt içiyorum.', audioLang: 'tr-TR', question: 'What is the speaker drinking?', choices: ['Water', 'Milk', 'Juice'], correctIndex: 1 },
  { id: 27, difficulty: 'easy', audioText: 'Üç elma aldım.', audioLang: 'tr-TR', question: 'How many apples?', choices: ['Two', 'Four', 'Three'], correctIndex: 2 },
  { id: 28, difficulty: 'easy', audioText: 'Masada otur.', audioLang: 'tr-TR', question: 'What is the instruction?', choices: ['Sit at the table.', 'Stand up.', 'Go outside.'], correctIndex: 0 },
  { id: 29, difficulty: 'easy', audioText: 'Çiçekler güzel.', audioLang: 'tr-TR', question: 'What is beautiful?', choices: ['Trees', 'Flowers', 'Birds'], correctIndex: 1 },
  { id: 30, difficulty: 'easy', audioText: 'Dışarıda güneş var.', audioLang: 'tr-TR', question: 'What is outside?', choices: ['Rain', 'Snow', 'Sunshine'], correctIndex: 2 },
  { id: 31, difficulty: 'easy', audioText: 'Peynir yiyorum.', audioLang: 'tr-TR', question: 'What is the speaker eating?', choices: ['Cheese', 'Meat', 'Bread'], correctIndex: 0 },
  { id: 32, difficulty: 'easy', audioText: 'Arabam kırmızı.', audioLang: 'tr-TR', question: 'What color is the car?', choices: ['Blue', 'Red', 'Black'], correctIndex: 1 },
  { id: 33, difficulty: 'easy', audioText: 'Kızım okula gidiyor.', audioLang: 'tr-TR', question: 'Who is going to school?', choices: ['Son', 'Mother', 'Daughter'], correctIndex: 2 },
  { id: 34, difficulty: 'easy', audioText: 'Lütfen yardım edin.', audioLang: 'tr-TR', question: 'What is being asked?', choices: ['Please help.', 'Thank you.', 'Goodbye.'], correctIndex: 0 },
  { id: 35, difficulty: 'easy', audioText: 'Telefon çalıyor.', audioLang: 'tr-TR', question: 'What is ringing?', choices: ['Doorbell', 'Phone', 'Alarm'], correctIndex: 1 },
  { id: 36, difficulty: 'easy', audioText: 'Yağmur yağıyor.', audioLang: 'tr-TR', question: 'What is happening?', choices: ['It is snowing.', 'It is sunny.', 'It is raining.'], correctIndex: 2 },
  { id: 37, difficulty: 'easy', audioText: 'Hayır, istemiyorum.', audioLang: 'tr-TR', question: 'What is the response?', choices: ['No, I don\'t want it.', 'Yes, I want it.', 'Maybe.'], correctIndex: 0 },
  { id: 38, difficulty: 'easy', audioText: 'Saçlarım siyah.', audioLang: 'tr-TR', question: 'What color is the hair?', choices: ['Brown', 'Black', 'Blonde'], correctIndex: 1 },
  { id: 39, difficulty: 'easy', audioText: 'Bugün pazartesi.', audioLang: 'tr-TR', question: 'What day is it?', choices: ['Friday', 'Sunday', 'Monday'], correctIndex: 2 },
  { id: 40, difficulty: 'easy', audioText: 'Çantamı unuttum.', audioLang: 'tr-TR', question: 'What did the speaker forget?', choices: ['Their bag', 'Their phone', 'Their key'], correctIndex: 0 },

  /* ── MEDIUM (40 prompts) ─────────────────── */
  { id: 41, difficulty: 'medium', audioText: 'Yarın okula gideceğim.', audioLang: 'tr-TR', question: 'When is the speaker going to school?', choices: ['Yesterday', 'Tomorrow', 'Today'], correctIndex: 1 },
  { id: 42, difficulty: 'medium', audioText: 'Saat kaç? Saat üç.', audioLang: 'tr-TR', question: 'What time is it?', choices: ['Two o\'clock', 'Four o\'clock', 'Three o\'clock'], correctIndex: 2 },
  { id: 43, difficulty: 'medium', audioText: 'Markete gidip ekmek alacağım.', audioLang: 'tr-TR', question: 'Where is the speaker going?', choices: ['To the market', 'To the hospital', 'To the park'], correctIndex: 0 },
  { id: 44, difficulty: 'medium', audioText: 'Annem çok güzel yemek yapar.', audioLang: 'tr-TR', question: 'Who cooks well?', choices: ['Father', 'Mother', 'Sister'], correctIndex: 1 },
  { id: 45, difficulty: 'medium', audioText: 'Kış geldi, hava çok soğuk.', audioLang: 'tr-TR', question: 'What season is it?', choices: ['Summer', 'Spring', 'Winter'], correctIndex: 2 },
  { id: 46, difficulty: 'medium', audioText: 'Kahvaltıda peynir ve zeytin yedim.', audioLang: 'tr-TR', question: 'What meal is mentioned?', choices: ['Breakfast', 'Lunch', 'Dinner'], correctIndex: 0 },
  { id: 47, difficulty: 'medium', audioText: 'İki kardeşim var, biri büyük biri küçük.', audioLang: 'tr-TR', question: 'How many siblings does the speaker have?', choices: ['One', 'Two', 'Three'], correctIndex: 1 },
  { id: 48, difficulty: 'medium', audioText: 'Otobüs durağı nerede?', audioLang: 'tr-TR', question: 'What is the speaker looking for?', choices: ['A restaurant', 'A school', 'A bus stop'], correctIndex: 2 },
  { id: 49, difficulty: 'medium', audioText: 'Dün akşam film izledim.', audioLang: 'tr-TR', question: 'What did the speaker do last night?', choices: ['Watched a movie', 'Read a book', 'Went for a walk'], correctIndex: 0 },
  { id: 50, difficulty: 'medium', audioText: 'Bu kitap çok ilginç, okumalısın.', audioLang: 'tr-TR', question: 'What does the speaker recommend?', choices: ['A movie', 'A book', 'A song'], correctIndex: 1 },
  { id: 51, difficulty: 'medium', audioText: 'Her sabah saat yedide kalkıyorum.', audioLang: 'tr-TR', question: 'What time does the speaker wake up?', choices: ['6 AM', 'Eight', '7 AM'], correctIndex: 2 },
  { id: 52, difficulty: 'medium', audioText: 'Çarşamba günü toplantımız var.', audioLang: 'tr-TR', question: 'When is the meeting?', choices: ['Wednesday', 'Thursday', 'Friday'], correctIndex: 0 },
  { id: 53, difficulty: 'medium', audioText: 'Eczaneden ilaç aldım.', audioLang: 'tr-TR', question: 'Where did the speaker go?', choices: ['Market', 'Pharmacy', 'Hospital'], correctIndex: 1 },
  { id: 54, difficulty: 'medium', audioText: 'Komşumuz yeni bir araba aldı.', audioLang: 'tr-TR', question: 'What did the neighbor buy?', choices: ['A house', 'A bike', 'A car'], correctIndex: 2 },
  { id: 55, difficulty: 'medium', audioText: 'Akşam yemeğini ben pişireceğim.', audioLang: 'tr-TR', question: 'Who will cook dinner?', choices: ['The speaker', 'Mother', 'Father'], correctIndex: 0 },
  { id: 56, difficulty: 'medium', audioText: 'Haftada üç gün spor yapıyorum.', audioLang: 'tr-TR', question: 'How often does the speaker exercise?', choices: ['Twice a week', 'Three times a week', 'Every day'], correctIndex: 1 },
  { id: 57, difficulty: 'medium', audioText: 'Parkta çocuklar oynuyor.', audioLang: 'tr-TR', question: 'Who is playing in the park?', choices: ['Dogs', 'Adults', 'Children'], correctIndex: 2 },
  { id: 58, difficulty: 'medium', audioText: 'Kuzenlerim yarın gelecek.', audioLang: 'tr-TR', question: 'Who is coming tomorrow?', choices: ['Cousins', 'Friends', 'Grandparents'], correctIndex: 0 },
  { id: 59, difficulty: 'medium', audioText: 'Bilet fiyatı ne kadar?', audioLang: 'tr-TR', question: 'What is the speaker asking about?', choices: ['Time', 'Ticket price', 'Direction'], correctIndex: 1 },
  { id: 60, difficulty: 'medium', audioText: 'Yaz tatilinde denize gideceğiz.', audioLang: 'tr-TR', question: 'What will they do in summer?', choices: ['Go to mountains', 'Stay home', 'Go to the sea'], correctIndex: 2 },
  { id: 61, difficulty: 'medium', audioText: 'Dün marketten meyve aldım.', audioLang: 'tr-TR', question: 'What did the speaker buy?', choices: ['Fruit', 'Vegetables', 'Bread'], correctIndex: 0 },
  { id: 62, difficulty: 'medium', audioText: 'Abim üniversitede okuyor.', audioLang: 'tr-TR', question: 'Where does the brother study?', choices: ['High school', 'University', 'Middle school'], correctIndex: 1 },
  { id: 63, difficulty: 'medium', audioText: 'Yeni bir telefon almak istiyorum.', audioLang: 'tr-TR', question: 'What does the speaker want to buy?', choices: ['A car', 'A computer', 'A phone'], correctIndex: 2 },
  { id: 64, difficulty: 'medium', audioText: 'Bugün doktora gideceğim.', audioLang: 'tr-TR', question: 'Where is the speaker going today?', choices: ['To the doctor', 'To school', 'To work'], correctIndex: 0 },
  { id: 65, difficulty: 'medium', audioText: 'Soğuk hava yüzünden evde kaldım.', audioLang: 'tr-TR', question: 'Why did the speaker stay home?', choices: ['Rain', 'Cold weather', 'Work'], correctIndex: 1 },
  { id: 66, difficulty: 'medium', audioText: 'Müzik dinlemeyi çok seviyorum.', audioLang: 'tr-TR', question: 'What does the speaker love?', choices: ['Reading', 'Cooking', 'Listening to music'], correctIndex: 2 },
  { id: 67, difficulty: 'medium', audioText: 'Hafta sonu pikniğe gidelim mi?', audioLang: 'tr-TR', question: 'What is suggested for the weekend?', choices: ['A picnic', 'A movie', 'Shopping'], correctIndex: 0 },
  { id: 68, difficulty: 'medium', audioText: 'Dedem seksen yaşında.', audioLang: 'tr-TR', question: 'How old is the grandfather?', choices: ['70', '80', '90'], correctIndex: 1 },
  { id: 69, difficulty: 'medium', audioText: 'Pencereden kar görüyorum.', audioLang: 'tr-TR', question: 'What can the speaker see from the window?', choices: ['Rain', 'Sunshine', 'Snow'], correctIndex: 2 },
  { id: 70, difficulty: 'medium', audioText: 'Sınıfta otuz öğrenci var.', audioLang: 'tr-TR', question: 'How many students are in the class?', choices: ['Thirty', 'Twenty', 'Forty'], correctIndex: 0 },
  { id: 71, difficulty: 'medium', audioText: 'Cumartesi günü alışverişe çıkacağız.', audioLang: 'tr-TR', question: 'What will they do on Saturday?', choices: ['Study', 'Go shopping', 'Exercise'], correctIndex: 1 },
  { id: 72, difficulty: 'medium', audioText: 'Akşam yemeğinde tavuk var.', audioLang: 'tr-TR', question: 'What is for dinner?', choices: ['Fish', 'Beef', 'Chicken'], correctIndex: 2 },
  { id: 73, difficulty: 'medium', audioText: 'Ders saat dokuzda başlıyor.', audioLang: 'tr-TR', question: 'When does class start?', choices: ['9 o\'clock', '10 o\'clock', '8 o\'clock'], correctIndex: 0 },
  { id: 74, difficulty: 'medium', audioText: 'Annemin doğum günü mayısta.', audioLang: 'tr-TR', question: 'When is the mother\'s birthday?', choices: ['April', 'May', 'June'], correctIndex: 1 },
  { id: 75, difficulty: 'medium', audioText: 'Sokakta bir kedi gördüm.', audioLang: 'tr-TR', question: 'What did the speaker see on the street?', choices: ['A dog', 'A bird', 'A cat'], correctIndex: 2 },
  { id: 76, difficulty: 'medium', audioText: 'Her gün yarım saat kitap okuyorum.', audioLang: 'tr-TR', question: 'How long does the speaker read daily?', choices: ['Half an hour', 'One hour', 'Fifteen minutes'], correctIndex: 0 },
  { id: 77, difficulty: 'medium', audioText: 'Okulda İngilizce öğreniyoruz.', audioLang: 'tr-TR', question: 'What language are they learning?', choices: ['French', 'English', 'German'], correctIndex: 1 },
  { id: 78, difficulty: 'medium', audioText: 'Bahçede çiçekler açmış.', audioLang: 'tr-TR', question: 'What happened in the garden?', choices: ['Trees fell', 'It rained', 'Flowers bloomed'], correctIndex: 2 },
  { id: 79, difficulty: 'medium', audioText: 'İstanbul çok kalabalık bir şehir.', audioLang: 'tr-TR', question: 'How is Istanbul described?', choices: ['Very crowded', 'Very quiet', 'Very small'], correctIndex: 0 },
  { id: 80, difficulty: 'medium', audioText: 'Patronum bugün izin verdi.', audioLang: 'tr-TR', question: 'What did the boss give?', choices: ['A raise', 'A day off', 'A task'], correctIndex: 1 },

  /* ── HARD (40 prompts) ───────────────────── */
  { id: 81, difficulty: 'hard', audioText: 'Geçen hafta İstanbul\'a gittim ve çok güzel vakit geçirdim.', audioLang: 'tr-TR', question: 'Where did the speaker go last week?', choices: ['Ankara', 'İzmir', 'İstanbul'], correctIndex: 2 },
  { id: 82, difficulty: 'hard', audioText: 'Doktor bana her gün meyve yememi söyledi.', audioLang: 'tr-TR', question: 'What did the doctor advise?', choices: ['Eat fruit every day', 'Exercise more', 'Drink more water'], correctIndex: 0 },
  { id: 83, difficulty: 'hard', audioText: 'Türkçe öğrenmek istiyorum çünkü Türkiye\'de yaşamak istiyorum.', audioLang: 'tr-TR', question: 'Why does the speaker want to learn Turkish?', choices: ['For a job', 'To live in Turkey', 'For school'], correctIndex: 1 },
  { id: 84, difficulty: 'hard', audioText: 'Hava çok sıcak olduğu için denize gittik.', audioLang: 'tr-TR', question: 'Why did they go to the sea?', choices: ['It was cold', 'It was raining', 'It was very hot'], correctIndex: 2 },
  { id: 85, difficulty: 'hard', audioText: 'Cumartesi günü arkadaşlarımla pikniğe gideceğiz.', audioLang: 'tr-TR', question: 'What are they doing on Saturday?', choices: ['Going on a picnic', 'Going to a concert', 'Going shopping'], correctIndex: 0 },
  { id: 86, difficulty: 'hard', audioText: 'Babam emekli oldu ve şimdi bahçede çalışıyor.', audioLang: 'tr-TR', question: 'What does the father do now?', choices: ['He teaches', 'He works in the garden', 'He travels'], correctIndex: 1 },
  { id: 87, difficulty: 'hard', audioText: 'Müzik dinlemeyi seviyorum, özellikle Türk müziği.', audioLang: 'tr-TR', question: 'What kind of music does the speaker prefer?', choices: ['Classical', 'Rock', 'Turkish music'], correctIndex: 2 },
  { id: 88, difficulty: 'hard', audioText: 'Her sabah erkenden kalkıp spor yapıyorum.', audioLang: 'tr-TR', question: 'What does the speaker do every morning?', choices: ['Exercises early', 'Reads the newspaper', 'Cooks breakfast'], correctIndex: 0 },
  { id: 89, difficulty: 'hard', audioText: 'Tatilde ailecek Antalya\'ya gideceğiz, çok heyecanlıyım.', audioLang: 'tr-TR', question: 'How does the speaker feel about the holiday?', choices: ['Worried', 'Excited', 'Tired'], correctIndex: 1 },
  { id: 90, difficulty: 'hard', audioText: 'Yeni bir iş buldum, pazartesi başlıyorum.', audioLang: 'tr-TR', question: 'When does the new job start?', choices: ['Friday', 'Wednesday', 'Monday'], correctIndex: 2 },
  { id: 91, difficulty: 'hard', audioText: 'Akşam yemeğinden sonra ailecek film izliyoruz.', audioLang: 'tr-TR', question: 'When do they watch a movie?', choices: ['After dinner', 'Before breakfast', 'During lunch'], correctIndex: 0 },
  { id: 92, difficulty: 'hard', audioText: 'Geçen yıl üniversiteden mezun oldum ve iş aramaya başladım.', audioLang: 'tr-TR', question: 'What did the speaker do last year?', choices: ['Started school', 'Graduated from university', 'Moved to a new city'], correctIndex: 1 },
  { id: 93, difficulty: 'hard', audioText: 'Komşumuzun oğlu İngiltere\'de master yapıyor.', audioLang: 'tr-TR', question: 'Where is the neighbor\'s son studying?', choices: ['Germany', 'France', 'England'], correctIndex: 2 },
  { id: 94, difficulty: 'hard', audioText: 'Çevre kirliliği dünya için büyük bir tehdit.', audioLang: 'tr-TR', question: 'What is described as a threat?', choices: ['Environmental pollution', 'War', 'Poverty'], correctIndex: 0 },
  { id: 95, difficulty: 'hard', audioText: 'Sağlıklı beslenme alışkanlıkları edinmek çok önemli.', audioLang: 'tr-TR', question: 'What is important according to the speaker?', choices: ['Exercise', 'Healthy eating habits', 'Sleeping well'], correctIndex: 1 },
  { id: 96, difficulty: 'hard', audioText: 'Teknoloji sayesinde uzaktaki insanlarla kolayca iletişim kurabiliyoruz.', audioLang: 'tr-TR', question: 'What does technology help us do?', choices: ['Travel', 'Cook', 'Communicate easily'], correctIndex: 2 },
  { id: 97, difficulty: 'hard', audioText: 'Kütüphanede sessiz olmak gerekir çünkü insanlar ders çalışıyor.', audioLang: 'tr-TR', question: 'Why should you be quiet in the library?', choices: ['People are studying', 'People are sleeping', 'It is a rule'], correctIndex: 0 },
  { id: 98, difficulty: 'hard', audioText: 'Geçen hafta hem sınava çalıştım hem de spor yaptım.', audioLang: 'tr-TR', question: 'What did the speaker do last week?', choices: ['Only studied', 'Studied and exercised', 'Only exercised'], correctIndex: 1 },
  { id: 99, difficulty: 'hard', audioText: 'Büyükşehirlerde trafik sorunu gittikçe artıyor.', audioLang: 'tr-TR', question: 'What problem is increasing in big cities?', choices: ['Noise', 'Crime', 'Traffic'], correctIndex: 2 },
  { id: 100, difficulty: 'hard', audioText: 'Türk mutfağı dünyada en çok bilinen mutfaklardan biridir.', audioLang: 'tr-TR', question: 'What is Turkish cuisine described as?', choices: ['One of the best-known cuisines', 'The oldest cuisine', 'The simplest cuisine'], correctIndex: 0 },
  { id: 101, difficulty: 'hard', audioText: 'Yabancı dil öğrenmek için en iyi yöntem her gün pratik yapmaktır.', audioLang: 'tr-TR', question: 'What is the best way to learn a language?', choices: ['Reading books', 'Practicing every day', 'Watching TV'], correctIndex: 1 },
  { id: 102, difficulty: 'hard', audioText: 'İklim değişikliği nedeniyle kuraklık artıyor.', audioLang: 'tr-TR', question: 'What is increasing due to climate change?', choices: ['Rainfall', 'Cold', 'Drought'], correctIndex: 2 },
  { id: 103, difficulty: 'hard', audioText: 'Bu projeyi tamamlamak için en az iki hafta daha gerekiyor.', audioLang: 'tr-TR', question: 'How much more time is needed?', choices: ['At least two more weeks', 'One month', 'Three days'], correctIndex: 0 },
  { id: 104, difficulty: 'hard', audioText: 'Ailem benimle çok gurur duyuyor çünkü sınavı birinci olarak geçtim.', audioLang: 'tr-TR', question: 'Why is the family proud?', choices: ['Got a new job', 'Passed the exam first', 'Won a competition'], correctIndex: 1 },
  { id: 105, difficulty: 'hard', audioText: 'Geri dönüşüm sayesinde doğal kaynakları koruyabiliriz.', audioLang: 'tr-TR', question: 'What can we protect through recycling?', choices: ['Money', 'Time', 'Natural resources'], correctIndex: 2 },
  { id: 106, difficulty: 'hard', audioText: 'Toplantıya katılmak için yarın sabah erken yola çıkmam gerekiyor.', audioLang: 'tr-TR', question: 'Why is the speaker leaving early?', choices: ['To attend a meeting', 'To catch a flight', 'To visit family'], correctIndex: 0 },
  { id: 107, difficulty: 'hard', audioText: 'Bu restoranın yemekleri hem lezzetli hem de uygun fiyatlı.', audioLang: 'tr-TR', question: 'How is the restaurant described?', choices: ['Expensive', 'Delicious and affordable', 'Only good-looking'], correctIndex: 1 },
  { id: 108, difficulty: 'hard', audioText: 'İnternet üzerinden alışveriş yapmak günümüzde çok yaygınlaştı.', audioLang: 'tr-TR', question: 'What has become widespread?', choices: ['Reading books', 'Traveling', 'Online shopping'], correctIndex: 2 },
  { id: 109, difficulty: 'hard', audioText: 'Öğretmenimiz bize her hafta bir kitap okumamızı tavsiye etti.', audioLang: 'tr-TR', question: 'What did the teacher recommend?', choices: ['Reading a book every week', 'Watching a movie', 'Exercising daily'], correctIndex: 0 },
  { id: 110, difficulty: 'hard', audioText: 'Deprem bölgesine yardım göndermek için kampanya başlatıldı.', audioLang: 'tr-TR', question: 'What was the campaign for?', choices: ['Education', 'Sending aid to earthquake zone', 'Building new roads'], correctIndex: 1 },
  { id: 111, difficulty: 'hard', audioText: 'Stres yönetimi için düzenli egzersiz ve meditasyon öneriliyor.', audioLang: 'tr-TR', question: 'What is recommended for stress management?', choices: ['Eating more', 'Sleeping more', 'Regular exercise and meditation'], correctIndex: 2 },
  { id: 112, difficulty: 'hard', audioText: 'Yeni açılan kütüphane şehrin en büyük kültür merkezi oldu.', audioLang: 'tr-TR', question: 'What became the city\'s largest cultural center?', choices: ['The new library', 'The museum', 'The theater'], correctIndex: 0 },
  { id: 113, difficulty: 'hard', audioText: 'Okulumuzda hem Türkçe hem de İngilizce eğitim veriliyor.', audioLang: 'tr-TR', question: 'What languages are taught?', choices: ['Only Turkish', 'Turkish and English', 'English and French'], correctIndex: 1 },
  { id: 114, difficulty: 'hard', audioText: 'Sabahları kahvaltı yapmadan çıkmak sağlığa zararlıdır.', audioLang: 'tr-TR', question: 'What is harmful to health?', choices: ['Eating too much', 'Sleeping late', 'Skipping breakfast'], correctIndex: 2 },
  { id: 115, difficulty: 'hard', audioText: 'Sosyal medya kullanımı, özellikle gençler arasında artmaktadır.', audioLang: 'tr-TR', question: 'What is increasing among youth?', choices: ['Social media use', 'Reading books', 'Outdoor sports'], correctIndex: 0 },
  { id: 116, difficulty: 'hard', audioText: 'Bu yıl tatilimizi Kapadokya\'da geçirmeyi planlıyoruz, balon turuna katılacağız.', audioLang: 'tr-TR', question: 'What activity are they planning?', choices: ['Hiking', 'A balloon tour', 'Swimming'], correctIndex: 1 },
  { id: 117, difficulty: 'hard', audioText: 'Ekonomik kriz nedeniyle birçok küçük işletme kapanmak zorunda kaldı.', audioLang: 'tr-TR', question: 'What happened because of the economic crisis?', choices: ['Prices dropped', 'Tourism increased', 'Small businesses had to close'], correctIndex: 2 },
  { id: 118, difficulty: 'hard', audioText: 'Başarılı olmak için düzenli çalışmak ve sabırlı olmak gerekir.', audioLang: 'tr-TR', question: 'What is needed for success?', choices: ['Regular work and patience', 'Luck', 'Money'], correctIndex: 0 },
  { id: 119, difficulty: 'hard', audioText: 'Kültürel farklılıklar toplumları zenginleştirir ve geliştir.', audioLang: 'tr-TR', question: 'What do cultural differences do to societies?', choices: ['Weaken them', 'Enrich and develop them', 'Have no effect'], correctIndex: 1 },
  { id: 120, difficulty: 'hard', audioText: 'Yapay zeka teknolojisi eğitimden sağlığa birçok alanda kullanılıyor.', audioLang: 'tr-TR', question: 'In which areas is AI used?', choices: ['Only education', 'Only healthcare', 'Many areas from education to health'], correctIndex: 2 },
]
