import type { Difficulty } from '@/gameplay'

export interface SpeakingPrompt {
  id: number
  difficulty: Difficulty
  sentence: string
  translation: string
}

export const SPEAKING_PROMPTS: SpeakingPrompt[] = [
  /* ── EASY (40 prompts) ───────────────────── */
  { id: 1, difficulty: 'easy', sentence: 'Merhaba', translation: 'Hello' },
  { id: 2, difficulty: 'easy', sentence: 'Nasılsın?', translation: 'How are you?' },
  { id: 3, difficulty: 'easy', sentence: 'Teşekkür ederim', translation: 'Thank you' },
  { id: 4, difficulty: 'easy', sentence: 'Günaydın', translation: 'Good morning' },
  { id: 5, difficulty: 'easy', sentence: 'İyi geceler', translation: 'Good night' },
  { id: 6, difficulty: 'easy', sentence: 'Evet, anlıyorum', translation: 'Yes, I understand' },
  { id: 7, difficulty: 'easy', sentence: 'Hayır, bilmiyorum', translation: 'No, I don\'t know' },
  { id: 8, difficulty: 'easy', sentence: 'Lütfen yardım edin', translation: 'Please help' },
  { id: 9, difficulty: 'easy', sentence: 'Su istiyorum', translation: 'I want water' },
  { id: 10, difficulty: 'easy', sentence: 'Hoşça kal', translation: 'Goodbye' },
  { id: 11, difficulty: 'easy', sentence: 'İyi akşamlar', translation: 'Good evening' },
  { id: 12, difficulty: 'easy', sentence: 'Özür dilerim', translation: 'I am sorry' },
  { id: 13, difficulty: 'easy', sentence: 'Affedersiniz', translation: 'Excuse me' },
  { id: 14, difficulty: 'easy', sentence: 'Hoş geldiniz', translation: 'Welcome' },
  { id: 15, difficulty: 'easy', sentence: 'Tabii ki', translation: 'Of course' },
  { id: 16, difficulty: 'easy', sentence: 'Bir dakika', translation: 'One moment' },
  { id: 17, difficulty: 'easy', sentence: 'Bu ne?', translation: 'What is this?' },
  { id: 18, difficulty: 'easy', sentence: 'Çok güzel', translation: 'Very beautiful' },
  { id: 19, difficulty: 'easy', sentence: 'Aç mısın?', translation: 'Are you hungry?' },
  { id: 20, difficulty: 'easy', sentence: 'Hadi gidelim', translation: 'Let\'s go' },
  { id: 21, difficulty: 'easy', sentence: 'Ne zaman?', translation: 'When?' },
  { id: 22, difficulty: 'easy', sentence: 'Nerede?', translation: 'Where?' },
  { id: 23, difficulty: 'easy', sentence: 'Kim bu?', translation: 'Who is this?' },
  { id: 24, difficulty: 'easy', sentence: 'Kaç tane?', translation: 'How many?' },
  { id: 25, difficulty: 'easy', sentence: 'Tamam', translation: 'Okay' },
  { id: 26, difficulty: 'easy', sentence: 'Bana ver', translation: 'Give me' },
  { id: 27, difficulty: 'easy', sentence: 'Ben hazırım', translation: 'I am ready' },
  { id: 28, difficulty: 'easy', sentence: 'Dikkat et', translation: 'Be careful' },
  { id: 29, difficulty: 'easy', sentence: 'Hava güzel', translation: 'The weather is nice' },
  { id: 30, difficulty: 'easy', sentence: 'Çok teşekkürler', translation: 'Thanks a lot' },
  { id: 31, difficulty: 'easy', sentence: 'Ben iyiyim', translation: 'I am fine' },
  { id: 32, difficulty: 'easy', sentence: 'Kapıyı aç', translation: 'Open the door' },
  { id: 33, difficulty: 'easy', sentence: 'Gel buraya', translation: 'Come here' },
  { id: 34, difficulty: 'easy', sentence: 'Otur lütfen', translation: 'Sit down please' },
  { id: 35, difficulty: 'easy', sentence: 'Bana bak', translation: 'Look at me' },
  { id: 36, difficulty: 'easy', sentence: 'Ne istiyorsun?', translation: 'What do you want?' },
  { id: 37, difficulty: 'easy', sentence: 'Şimdi mi?', translation: 'Now?' },
  { id: 38, difficulty: 'easy', sentence: 'Elbette', translation: 'Certainly' },
  { id: 39, difficulty: 'easy', sentence: 'Çok iyi', translation: 'Very good' },
  { id: 40, difficulty: 'easy', sentence: 'Tebrikler', translation: 'Congratulations' },

  /* ── MEDIUM (40 prompts) ─────────────────── */
  { id: 41, difficulty: 'medium', sentence: 'Benim adım Ali', translation: 'My name is Ali' },
  { id: 42, difficulty: 'medium', sentence: 'Ben öğrenciyim', translation: 'I am a student' },
  { id: 43, difficulty: 'medium', sentence: 'Bugün hava güzel', translation: 'The weather is nice today' },
  { id: 44, difficulty: 'medium', sentence: 'Bir çay lütfen', translation: 'One tea, please' },
  { id: 45, difficulty: 'medium', sentence: 'Saat kaç?', translation: 'What time is it?' },
  { id: 46, difficulty: 'medium', sentence: 'Nereye gidiyorsun?', translation: 'Where are you going?' },
  { id: 47, difficulty: 'medium', sentence: 'Bugün ne yapacaksın?', translation: 'What will you do today?' },
  { id: 48, difficulty: 'medium', sentence: 'Markete gidiyorum', translation: 'I am going to the market' },
  { id: 49, difficulty: 'medium', sentence: 'Bu ne kadar?', translation: 'How much is this?' },
  { id: 50, difficulty: 'medium', sentence: 'Türkçe öğreniyorum', translation: 'I am learning Turkish' },
  { id: 51, difficulty: 'medium', sentence: 'Kahvaltı hazır mı?', translation: 'Is breakfast ready?' },
  { id: 52, difficulty: 'medium', sentence: 'Yarın sınav var', translation: 'There is an exam tomorrow' },
  { id: 53, difficulty: 'medium', sentence: 'Kardeşim çok küçük', translation: 'My sibling is very young' },
  { id: 54, difficulty: 'medium', sentence: 'Bu yemek çok lezzetli', translation: 'This food is very delicious' },
  { id: 55, difficulty: 'medium', sentence: 'Haftada iki gün spor yapıyorum', translation: 'I exercise twice a week' },
  { id: 56, difficulty: 'medium', sentence: 'Okulum eve yakın', translation: 'My school is close to home' },
  { id: 57, difficulty: 'medium', sentence: 'Dün çok yağmur yağdı', translation: 'It rained a lot yesterday' },
  { id: 58, difficulty: 'medium', sentence: 'Kitap okumayı seviyorum', translation: 'I like reading books' },
  { id: 59, difficulty: 'medium', sentence: 'Ailem çok büyük', translation: 'My family is very large' },
  { id: 60, difficulty: 'medium', sentence: 'Her gün süt içiyorum', translation: 'I drink milk every day' },
  { id: 61, difficulty: 'medium', sentence: 'En sevdiğim renk mavi', translation: 'My favorite color is blue' },
  { id: 62, difficulty: 'medium', sentence: 'Arkadaşım burada oturuyor', translation: 'My friend lives here' },
  { id: 63, difficulty: 'medium', sentence: 'Akşam yemeği ne?', translation: 'What is for dinner?' },
  { id: 64, difficulty: 'medium', sentence: 'Yeni bir telefon aldım', translation: 'I bought a new phone' },
  { id: 65, difficulty: 'medium', sentence: 'Tatilde nereye gideceksin?', translation: 'Where will you go on vacation?' },
  { id: 66, difficulty: 'medium', sentence: 'Bugün çok meşgulüm', translation: 'I am very busy today' },
  { id: 67, difficulty: 'medium', sentence: 'Annem çok güzel yemek yapar', translation: 'My mother cooks very well' },
  { id: 68, difficulty: 'medium', sentence: 'Doktora randevu aldım', translation: 'I made an appointment with the doctor' },
  { id: 69, difficulty: 'medium', sentence: 'Bu film çok güzel', translation: 'This movie is very good' },
  { id: 70, difficulty: 'medium', sentence: 'Park çok kalabalık', translation: 'The park is very crowded' },
  { id: 71, difficulty: 'medium', sentence: 'Öğleden sonra buluşalım', translation: 'Let\'s meet in the afternoon' },
  { id: 72, difficulty: 'medium', sentence: 'Çocuklar dışarıda oynuyor', translation: 'Children are playing outside' },
  { id: 73, difficulty: 'medium', sentence: 'İstanbul çok güzel bir şehir', translation: 'Istanbul is a very beautiful city' },
  { id: 74, difficulty: 'medium', sentence: 'Pazardan sebze aldım', translation: 'I bought vegetables from the market' },
  { id: 75, difficulty: 'medium', sentence: 'Bu gömlek bana çok büyük', translation: 'This shirt is too big for me' },
  { id: 76, difficulty: 'medium', sentence: 'Bilgisayarım bozuldu', translation: 'My computer is broken' },
  { id: 77, difficulty: 'medium', sentence: 'Yarın erken kalkacağım', translation: 'I will wake up early tomorrow' },
  { id: 78, difficulty: 'medium', sentence: 'Müzik dinlemeyi seviyorum', translation: 'I love listening to music' },
  { id: 79, difficulty: 'medium', sentence: 'Okulda İngilizce öğreniyoruz', translation: 'We learn English at school' },
  { id: 80, difficulty: 'medium', sentence: 'Komşumuz çok iyi insanlar', translation: 'Our neighbors are very good people' },

  /* ── HARD (40 prompts) ───────────────────── */
  { id: 81, difficulty: 'hard', sentence: 'Yarın okula gideceğim', translation: 'I will go to school tomorrow' },
  { id: 82, difficulty: 'hard', sentence: 'Dün akşam film izledim', translation: 'I watched a movie last night' },
  { id: 83, difficulty: 'hard', sentence: 'İki kardeşim var', translation: 'I have two siblings' },
  { id: 84, difficulty: 'hard', sentence: 'Otobüs durağı nerede?', translation: 'Where is the bus stop?' },
  { id: 85, difficulty: 'hard', sentence: 'Kahvaltıda peynir yedim', translation: 'I ate cheese for breakfast' },
  { id: 86, difficulty: 'hard', sentence: 'Her gün spor yapıyorum', translation: 'I exercise every day' },
  { id: 87, difficulty: 'hard', sentence: 'Bu kitap çok ilginç', translation: 'This book is very interesting' },
  { id: 88, difficulty: 'hard', sentence: 'Tatilde denize gittik', translation: 'We went to the sea on vacation' },
  { id: 89, difficulty: 'hard', sentence: 'Yeni bir iş buldum', translation: 'I found a new job' },
  { id: 90, difficulty: 'hard', sentence: 'Geçen hafta İstanbul\'a gittim', translation: 'I went to Istanbul last week' },
  { id: 91, difficulty: 'hard', sentence: 'Sağlıklı beslenme çok önemli', translation: 'Healthy eating is very important' },
  { id: 92, difficulty: 'hard', sentence: 'Çevre kirliliği büyük bir sorun', translation: 'Environmental pollution is a big problem' },
  { id: 93, difficulty: 'hard', sentence: 'Yabancı dil öğrenmek faydalıdır', translation: 'Learning a foreign language is useful' },
  { id: 94, difficulty: 'hard', sentence: 'Teknoloji hayatımızı kolaylaştırıyor', translation: 'Technology makes our lives easier' },
  { id: 95, difficulty: 'hard', sentence: 'Üniversitede mühendislik okuyorum', translation: 'I study engineering at university' },
  { id: 96, difficulty: 'hard', sentence: 'Kütüphanede sessiz olmak lazım', translation: 'You need to be quiet in the library' },
  { id: 97, difficulty: 'hard', sentence: 'Babam emekli oldu', translation: 'My father retired' },
  { id: 98, difficulty: 'hard', sentence: 'Her sabah erkenden kalkıyorum', translation: 'I wake up early every morning' },
  { id: 99, difficulty: 'hard', sentence: 'Ailem ile tatile gidiyoruz', translation: 'We are going on vacation with my family' },
  { id: 100, difficulty: 'hard', sentence: 'Geri dönüşüm yapmalıyız', translation: 'We should recycle' },
  { id: 101, difficulty: 'hard', sentence: 'İklim değişikliği ciddi bir sorun', translation: 'Climate change is a serious problem' },
  { id: 102, difficulty: 'hard', sentence: 'Toplantıya katılmam gerekiyor', translation: 'I need to attend the meeting' },
  { id: 103, difficulty: 'hard', sentence: 'İngilizce konuşmayı geliştirmek istiyorum', translation: 'I want to improve my English speaking' },
  { id: 104, difficulty: 'hard', sentence: 'Türk mutfağı çok zengindir', translation: 'Turkish cuisine is very rich' },
  { id: 105, difficulty: 'hard', sentence: 'Başarılı olmak için çok çalışmak gerekir', translation: 'You need to work hard to be successful' },
  { id: 106, difficulty: 'hard', sentence: 'Kültürel farklılıkları anlamak önemli', translation: 'Understanding cultural differences is important' },
  { id: 107, difficulty: 'hard', sentence: 'Sosyal medya kullanımı artıyor', translation: 'Social media use is increasing' },
  { id: 108, difficulty: 'hard', sentence: 'Öğretmenimiz çok sabırlı biri', translation: 'Our teacher is a very patient person' },
  { id: 109, difficulty: 'hard', sentence: 'Düzenli egzersiz sağlık için faydalı', translation: 'Regular exercise is good for health' },
  { id: 110, difficulty: 'hard', sentence: 'Depremden sonra yardım kampanyası başladı', translation: 'A relief campaign started after the earthquake' },
  { id: 111, difficulty: 'hard', sentence: 'Yapay zeka birçok alanda kullanılıyor', translation: 'Artificial intelligence is used in many areas' },
  { id: 112, difficulty: 'hard', sentence: 'Ekonomik kriz küçük işletmeleri etkiliyor', translation: 'The economic crisis affects small businesses' },
  { id: 113, difficulty: 'hard', sentence: 'Doğa yürüyüşü yapmayı seviyorum', translation: 'I like going on nature walks' },
  { id: 114, difficulty: 'hard', sentence: 'Yeni projem çok heyecan verici', translation: 'My new project is very exciting' },
  { id: 115, difficulty: 'hard', sentence: 'Geleneksel Türk kahvesi çok özel', translation: 'Traditional Turkish coffee is very special' },
  { id: 116, difficulty: 'hard', sentence: 'Araştırma sonuçları ilginç çıktı', translation: 'The research results turned out interesting' },
  { id: 117, difficulty: 'hard', sentence: 'Eğitim sistemi geliştirilmeli', translation: 'The education system should be improved' },
  { id: 118, difficulty: 'hard', sentence: 'Kapadokya\'da balon turu çok güzel', translation: 'Balloon tour in Cappadocia is very beautiful' },
  { id: 119, difficulty: 'hard', sentence: 'Sınava iyi hazırlanmak gerekir', translation: 'You need to prepare well for the exam' },
  { id: 120, difficulty: 'hard', sentence: 'Farklı kültürleri tanımak bizi zenginleştirir', translation: 'Getting to know different cultures enriches us' },
]
