import type { SQLiteDatabase } from 'expo-sqlite'
import { getDevNowIso } from '@/dev/clock'

const SEED_CARDS: { word: string; meaning: string }[] = [
  { word: 'hello', meaning: 'merhaba' },
  { word: 'goodbye', meaning: 'hoşça kal' },
  { word: 'thank you', meaning: 'teşekkür ederim' },
  { word: 'please', meaning: 'lütfen' },
  { word: 'yes', meaning: 'evet' },
  { word: 'no', meaning: 'hayır' },
  { word: 'water', meaning: 'su' },
  { word: 'bread', meaning: 'ekmek' },
  { word: 'milk', meaning: 'süt' },
  { word: 'tea', meaning: 'çay' },
  { word: 'coffee', meaning: 'kahve' },
  { word: 'food', meaning: 'yemek' },
  { word: 'house', meaning: 'ev' },
  { word: 'door', meaning: 'kapı' },
  { word: 'window', meaning: 'pencere' },
  { word: 'book', meaning: 'kitap' },
  { word: 'pen', meaning: 'kalem' },
  { word: 'paper', meaning: 'kağıt' },
  { word: 'table', meaning: 'masa' },
  { word: 'chair', meaning: 'sandalye' },
  { word: 'cat', meaning: 'kedi' },
  { word: 'dog', meaning: 'köpek' },
  { word: 'bird', meaning: 'kuş' },
  { word: 'fish', meaning: 'balık' },
  { word: 'tree', meaning: 'ağaç' },
  { word: 'flower', meaning: 'çiçek' },
  { word: 'sun', meaning: 'güneş' },
  { word: 'moon', meaning: 'ay' },
  { word: 'star', meaning: 'yıldız' },
  { word: 'rain', meaning: 'yağmur' },
  { word: 'snow', meaning: 'kar' },
  { word: 'wind', meaning: 'rüzgar' },
  { word: 'cloud', meaning: 'bulut' },
  { word: 'sky', meaning: 'gökyüzü' },
  { word: 'sea', meaning: 'deniz' },
  { word: 'mountain', meaning: 'dağ' },
  { word: 'river', meaning: 'nehir' },
  { word: 'lake', meaning: 'göl' },
  { word: 'garden', meaning: 'bahçe' },
  { word: 'road', meaning: 'yol' },
  { word: 'city', meaning: 'şehir' },
  { word: 'village', meaning: 'köy' },
  { word: 'school', meaning: 'okul' },
  { word: 'teacher', meaning: 'öğretmen' },
  { word: 'student', meaning: 'öğrenci' },
  { word: 'friend', meaning: 'arkadaş' },
  { word: 'family', meaning: 'aile' },
  { word: 'mother', meaning: 'anne' },
  { word: 'father', meaning: 'baba' },
  { word: 'child', meaning: 'çocuk' },
  { word: 'brother', meaning: 'erkek kardeş' },
  { word: 'sister', meaning: 'kız kardeş' },
  { word: 'baby', meaning: 'bebek' },
  { word: 'man', meaning: 'adam' },
  { word: 'woman', meaning: 'kadın' },
  { word: 'boy', meaning: 'oğlan' },
  { word: 'girl', meaning: 'kız' },
  { word: 'name', meaning: 'isim' },
  { word: 'age', meaning: 'yaş' },
  { word: 'hand', meaning: 'el' },
  { word: 'head', meaning: 'baş' },
  { word: 'eye', meaning: 'göz' },
  { word: 'ear', meaning: 'kulak' },
  { word: 'nose', meaning: 'burun' },
  { word: 'mouth', meaning: 'ağız' },
  { word: 'tooth', meaning: 'diş' },
  { word: 'hair', meaning: 'saç' },
  { word: 'heart', meaning: 'kalp' },
  { word: 'foot', meaning: 'ayak' },
  { word: 'arm', meaning: 'kol' },
  { word: 'leg', meaning: 'bacak' },
  { word: 'back', meaning: 'sırt' },
  { word: 'face', meaning: 'yüz' },
  { word: 'body', meaning: 'vücut' },
  { word: 'blood', meaning: 'kan' },
  { word: 'bone', meaning: 'kemik' },
  { word: 'skin', meaning: 'deri' },
  { word: 'red', meaning: 'kırmızı' },
  { word: 'blue', meaning: 'mavi' },
  { word: 'green', meaning: 'yeşil' },
  { word: 'yellow', meaning: 'sarı' },
  { word: 'white', meaning: 'beyaz' },
  { word: 'black', meaning: 'siyah' },
  { word: 'big', meaning: 'büyük' },
  { word: 'small', meaning: 'küçük' },
  { word: 'new', meaning: 'yeni' },
  { word: 'old', meaning: 'eski' },
  { word: 'good', meaning: 'iyi' },
  { word: 'bad', meaning: 'kötü' },
  { word: 'hot', meaning: 'sıcak' },
  { word: 'cold', meaning: 'soğuk' },
  { word: 'fast', meaning: 'hızlı' },
  { word: 'slow', meaning: 'yavaş' },
  { word: 'long', meaning: 'uzun' },
  { word: 'short', meaning: 'kısa' },
  { word: 'heavy', meaning: 'ağır' },
  { word: 'light', meaning: 'hafif' },
  { word: 'clean', meaning: 'temiz' },
  { word: 'dirty', meaning: 'kirli' },
  { word: 'happy', meaning: 'mutlu' },
  { word: 'sad', meaning: 'üzgün' },
  { word: 'hungry', meaning: 'aç' },
  { word: 'thirsty', meaning: 'susuz' },
  { word: 'tired', meaning: 'yorgun' },
  { word: 'strong', meaning: 'güçlü' },
  { word: 'weak', meaning: 'zayıf' },
  { word: 'beautiful', meaning: 'güzel' },
  { word: 'ugly', meaning: 'çirkin' },
  { word: 'easy', meaning: 'kolay' },
  { word: 'difficult', meaning: 'zor' },
  { word: 'full', meaning: 'dolu' },
  { word: 'empty', meaning: 'boş' },
  { word: 'open', meaning: 'açık' },
  { word: 'closed', meaning: 'kapalı' },
  { word: 'right', meaning: 'doğru' },
  { word: 'wrong', meaning: 'yanlış' },
  { word: 'near', meaning: 'yakın' },
  { word: 'far', meaning: 'uzak' },
  { word: 'eat', meaning: 'yemek' },
  { word: 'drink', meaning: 'içmek' },
  { word: 'sleep', meaning: 'uyumak' },
  { word: 'walk', meaning: 'yürümek' },
  { word: 'run', meaning: 'koşmak' },
  { word: 'sit', meaning: 'oturmak' },
  { word: 'stand', meaning: 'kalkmak' },
  { word: 'come', meaning: 'gelmek' },
  { word: 'go', meaning: 'gitmek' },
  { word: 'see', meaning: 'görmek' },
  { word: 'hear', meaning: 'duymak' },
  { word: 'speak', meaning: 'konuşmak' },
  { word: 'read', meaning: 'okumak' },
  { word: 'write', meaning: 'yazmak' },
  { word: 'learn', meaning: 'öğrenmek' },
  { word: 'know', meaning: 'bilmek' },
  { word: 'think', meaning: 'düşünmek' },
  { word: 'want', meaning: 'istemek' },
  { word: 'need', meaning: 'ihtiyaç duymak' },
  { word: 'love', meaning: 'sevmek' },
  { word: 'like', meaning: 'beğenmek' },
  { word: 'give', meaning: 'vermek' },
  { word: 'take', meaning: 'almak' },
  { word: 'buy', meaning: 'satın almak' },
  { word: 'sell', meaning: 'satmak' },
  { word: 'work', meaning: 'çalışmak' },
  { word: 'play', meaning: 'oynamak' },
  { word: 'sing', meaning: 'şarkı söylemek' },
  { word: 'dance', meaning: 'dans etmek' },
  { word: 'cook', meaning: 'pişirmek' },
  { word: 'wash', meaning: 'yıkamak' },
  { word: 'fly', meaning: 'uçmak' },
  { word: 'swim', meaning: 'yüzmek' },
  { word: 'drive', meaning: 'sürmek' },
  { word: 'open', meaning: 'açmak' },
  { word: 'close', meaning: 'kapatmak' },
  { word: 'begin', meaning: 'başlamak' },
  { word: 'finish', meaning: 'bitirmek' },
  { word: 'wait', meaning: 'beklemek' },
  { word: 'help', meaning: 'yardım etmek' },
  { word: 'ask', meaning: 'sormak' },
  { word: 'answer', meaning: 'cevap vermek' },
  { word: 'laugh', meaning: 'gülmek' },
  { word: 'cry', meaning: 'ağlamak' },
  { word: 'smile', meaning: 'gülümsemek' },
  { word: 'try', meaning: 'denemek' },
  { word: 'find', meaning: 'bulmak' },
  { word: 'lose', meaning: 'kaybetmek' },
  { word: 'win', meaning: 'kazanmak' },
  { word: 'send', meaning: 'göndermek' },
  { word: 'carry', meaning: 'taşımak' },
  { word: 'hold', meaning: 'tutmak' },
  { word: 'put', meaning: 'koymak' },
  { word: 'pull', meaning: 'çekmek' },
  { word: 'push', meaning: 'itmek' },
  { word: 'cut', meaning: 'kesmek' },
  { word: 'break', meaning: 'kırmak' },
  { word: 'build', meaning: 'inşa etmek' },
  { word: 'fix', meaning: 'tamir etmek' },
  { word: 'draw', meaning: 'çizmek' },
  { word: 'paint', meaning: 'boyamak' },
  { word: 'count', meaning: 'saymak' },
  { word: 'pay', meaning: 'ödemek' },
  { word: 'grow', meaning: 'büyümek' },
  { word: 'plant', meaning: 'ekmek' },
  { word: 'seed', meaning: 'tohum' },
  { word: 'leaf', meaning: 'yaprak' },
  { word: 'root', meaning: 'kök' },
  { word: 'fruit', meaning: 'meyve' },
  { word: 'apple', meaning: 'elma' },
  { word: 'orange', meaning: 'portakal' },
  { word: 'grape', meaning: 'üzüm' },
  { word: 'tomato', meaning: 'domates' },
  { word: 'onion', meaning: 'soğan' },
  { word: 'potato', meaning: 'patates' },
  { word: 'rice', meaning: 'pirinç' },
  { word: 'meat', meaning: 'et' },
  { word: 'chicken', meaning: 'tavuk' },
  { word: 'egg', meaning: 'yumurta' },
  { word: 'cheese', meaning: 'peynir' },
  { word: 'butter', meaning: 'tereyağı' },
  { word: 'sugar', meaning: 'şeker' },
  { word: 'salt', meaning: 'tuz' },
  { word: 'oil', meaning: 'yağ' },
  { word: 'money', meaning: 'para' },
  { word: 'price', meaning: 'fiyat' },
  { word: 'market', meaning: 'pazar' },
  { word: 'shop', meaning: 'dükkan' },
  { word: 'bag', meaning: 'çanta' },
  { word: 'key', meaning: 'anahtar' },
  { word: 'phone', meaning: 'telefon' },
  { word: 'clock', meaning: 'saat' },
  { word: 'morning', meaning: 'sabah' },
  { word: 'evening', meaning: 'akşam' },
  { word: 'night', meaning: 'gece' },
  { word: 'today', meaning: 'bugün' },
  { word: 'tomorrow', meaning: 'yarın' },
  { word: 'yesterday', meaning: 'dün' },
  { word: 'week', meaning: 'hafta' },
  { word: 'month', meaning: 'ay' },
  { word: 'year', meaning: 'yıl' },
]

const STARTER_PLANT = {
  speciesId: 'starter-fern',
  level: 1,
  xp: 0,
  health: 100,
  stage: 'seed',
}

export async function seedIfEmpty(db: SQLiteDatabase): Promise<void> {
  const now = getDevNowIso()

  const cardsCount = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) as count FROM srs_cards',
  )
  if ((cardsCount?.count ?? 0) === 0) {
    for (const card of SEED_CARDS) {
      await db.runAsync(
        'INSERT INTO srs_cards (word, meaning, example, interval, ease, dueDate, lapses) VALUES (?, ?, ?, ?, ?, ?, ?)',
        card.word,
        card.meaning,
        null,
        1,
        2.5,
        now,
        0,
      )
    }
  }

  const plantCount = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) as count FROM plants')
  if ((plantCount?.count ?? 0) === 0) {
    await db.runAsync(
      'INSERT INTO plants (speciesId, level, xp, health, stage, totalWater, totalSun, totalFertilizer, totalRoots, createdAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
      STARTER_PLANT.speciesId,
      STARTER_PLANT.level,
      STARTER_PLANT.xp,
      STARTER_PLANT.health,
      STARTER_PLANT.stage,
      0,
      0,
      0,
      0,
      now,
    )
  }

  const streakRow = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) as count FROM streaks')
  if ((streakRow?.count ?? 0) === 0) {
    await db.runAsync(
      'INSERT INTO streaks (id, currentStreak, lastSessionDate) VALUES (?, ?, ?)',
      1,
      0,
      null,
    )
  }
}
